// Code generated by protoc-gen-go. DO NOT EDIT.
// source: places.proto

package places

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Place struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	ImgURL               string   `protobuf:"bytes,5,opt,name=imgURL,proto3" json:"imgURL,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Place) Reset()         { *m = Place{} }
func (m *Place) String() string { return proto.CompactTextString(m) }
func (*Place) ProtoMessage()    {}
func (*Place) Descriptor() ([]byte, []int) {
	return fileDescriptor_0937d2e70aaf1027, []int{0}
}

func (m *Place) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Place.Unmarshal(m, b)
}
func (m *Place) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Place.Marshal(b, m, deterministic)
}
func (m *Place) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Place.Merge(m, src)
}
func (m *Place) XXX_Size() int {
	return xxx_messageInfo_Place.Size(m)
}
func (m *Place) XXX_DiscardUnknown() {
	xxx_messageInfo_Place.DiscardUnknown(m)
}

var xxx_messageInfo_Place proto.InternalMessageInfo

func (m *Place) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Place) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Place) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Place) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Place) GetImgURL() string {
	if m != nil {
		return m.ImgURL
	}
	return ""
}

type City struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *City) Reset()         { *m = City{} }
func (m *City) String() string { return proto.CompactTextString(m) }
func (*City) ProtoMessage()    {}
func (*City) Descriptor() ([]byte, []int) {
	return fileDescriptor_0937d2e70aaf1027, []int{1}
}

func (m *City) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_City.Unmarshal(m, b)
}
func (m *City) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_City.Marshal(b, m, deterministic)
}
func (m *City) XXX_Merge(src proto.Message) {
	xxx_messageInfo_City.Merge(m, src)
}
func (m *City) XXX_Size() int {
	return xxx_messageInfo_City.Size(m)
}
func (m *City) XXX_DiscardUnknown() {
	xxx_messageInfo_City.DiscardUnknown(m)
}

var xxx_messageInfo_City proto.InternalMessageInfo

func (m *City) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *City) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

// AddPlace
type AddPlaceRequest struct {
	CityName             string   `protobuf:"bytes,1,opt,name=cityName,proto3" json:"cityName,omitempty"`
	Place                *Place   `protobuf:"bytes,2,opt,name=place,proto3" json:"place,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddPlaceRequest) Reset()         { *m = AddPlaceRequest{} }
func (m *AddPlaceRequest) String() string { return proto.CompactTextString(m) }
func (*AddPlaceRequest) ProtoMessage()    {}
func (*AddPlaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0937d2e70aaf1027, []int{2}
}

func (m *AddPlaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPlaceRequest.Unmarshal(m, b)
}
func (m *AddPlaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPlaceRequest.Marshal(b, m, deterministic)
}
func (m *AddPlaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPlaceRequest.Merge(m, src)
}
func (m *AddPlaceRequest) XXX_Size() int {
	return xxx_messageInfo_AddPlaceRequest.Size(m)
}
func (m *AddPlaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPlaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddPlaceRequest proto.InternalMessageInfo

func (m *AddPlaceRequest) GetCityName() string {
	if m != nil {
		return m.CityName
	}
	return ""
}

func (m *AddPlaceRequest) GetPlace() *Place {
	if m != nil {
		return m.Place
	}
	return nil
}

type AddPlaceResponse struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddPlaceResponse) Reset()         { *m = AddPlaceResponse{} }
func (m *AddPlaceResponse) String() string { return proto.CompactTextString(m) }
func (*AddPlaceResponse) ProtoMessage()    {}
func (*AddPlaceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0937d2e70aaf1027, []int{3}
}

func (m *AddPlaceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPlaceResponse.Unmarshal(m, b)
}
func (m *AddPlaceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPlaceResponse.Marshal(b, m, deterministic)
}
func (m *AddPlaceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPlaceResponse.Merge(m, src)
}
func (m *AddPlaceResponse) XXX_Size() int {
	return xxx_messageInfo_AddPlaceResponse.Size(m)
}
func (m *AddPlaceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPlaceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddPlaceResponse proto.InternalMessageInfo

func (m *AddPlaceResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// GetCities
type GetCitiesRequest struct {
	Amount               uint64   `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Offset               uint64   `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCitiesRequest) Reset()         { *m = GetCitiesRequest{} }
func (m *GetCitiesRequest) String() string { return proto.CompactTextString(m) }
func (*GetCitiesRequest) ProtoMessage()    {}
func (*GetCitiesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0937d2e70aaf1027, []int{4}
}

func (m *GetCitiesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCitiesRequest.Unmarshal(m, b)
}
func (m *GetCitiesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCitiesRequest.Marshal(b, m, deterministic)
}
func (m *GetCitiesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCitiesRequest.Merge(m, src)
}
func (m *GetCitiesRequest) XXX_Size() int {
	return xxx_messageInfo_GetCitiesRequest.Size(m)
}
func (m *GetCitiesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCitiesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCitiesRequest proto.InternalMessageInfo

func (m *GetCitiesRequest) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *GetCitiesRequest) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type GetCitiesResponse struct {
	Cities               []*City  `protobuf:"bytes,1,rep,name=cities,proto3" json:"cities,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCitiesResponse) Reset()         { *m = GetCitiesResponse{} }
func (m *GetCitiesResponse) String() string { return proto.CompactTextString(m) }
func (*GetCitiesResponse) ProtoMessage()    {}
func (*GetCitiesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0937d2e70aaf1027, []int{5}
}

func (m *GetCitiesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCitiesResponse.Unmarshal(m, b)
}
func (m *GetCitiesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCitiesResponse.Marshal(b, m, deterministic)
}
func (m *GetCitiesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCitiesResponse.Merge(m, src)
}
func (m *GetCitiesResponse) XXX_Size() int {
	return xxx_messageInfo_GetCitiesResponse.Size(m)
}
func (m *GetCitiesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCitiesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCitiesResponse proto.InternalMessageInfo

func (m *GetCitiesResponse) GetCities() []*City {
	if m != nil {
		return m.Cities
	}
	return nil
}

// GetRandomPlaceByCityName
type GetRandomPlaceByCityNameRequest struct {
	CityName             string   `protobuf:"bytes,1,opt,name=cityName,proto3" json:"cityName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRandomPlaceByCityNameRequest) Reset()         { *m = GetRandomPlaceByCityNameRequest{} }
func (m *GetRandomPlaceByCityNameRequest) String() string { return proto.CompactTextString(m) }
func (*GetRandomPlaceByCityNameRequest) ProtoMessage()    {}
func (*GetRandomPlaceByCityNameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0937d2e70aaf1027, []int{6}
}

func (m *GetRandomPlaceByCityNameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRandomPlaceByCityNameRequest.Unmarshal(m, b)
}
func (m *GetRandomPlaceByCityNameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRandomPlaceByCityNameRequest.Marshal(b, m, deterministic)
}
func (m *GetRandomPlaceByCityNameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRandomPlaceByCityNameRequest.Merge(m, src)
}
func (m *GetRandomPlaceByCityNameRequest) XXX_Size() int {
	return xxx_messageInfo_GetRandomPlaceByCityNameRequest.Size(m)
}
func (m *GetRandomPlaceByCityNameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRandomPlaceByCityNameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRandomPlaceByCityNameRequest proto.InternalMessageInfo

func (m *GetRandomPlaceByCityNameRequest) GetCityName() string {
	if m != nil {
		return m.CityName
	}
	return ""
}

type GetRandomPlaceByCityNameResponse struct {
	Place                *Place   `protobuf:"bytes,1,opt,name=place,proto3" json:"place,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRandomPlaceByCityNameResponse) Reset()         { *m = GetRandomPlaceByCityNameResponse{} }
func (m *GetRandomPlaceByCityNameResponse) String() string { return proto.CompactTextString(m) }
func (*GetRandomPlaceByCityNameResponse) ProtoMessage()    {}
func (*GetRandomPlaceByCityNameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0937d2e70aaf1027, []int{7}
}

func (m *GetRandomPlaceByCityNameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRandomPlaceByCityNameResponse.Unmarshal(m, b)
}
func (m *GetRandomPlaceByCityNameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRandomPlaceByCityNameResponse.Marshal(b, m, deterministic)
}
func (m *GetRandomPlaceByCityNameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRandomPlaceByCityNameResponse.Merge(m, src)
}
func (m *GetRandomPlaceByCityNameResponse) XXX_Size() int {
	return xxx_messageInfo_GetRandomPlaceByCityNameResponse.Size(m)
}
func (m *GetRandomPlaceByCityNameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRandomPlaceByCityNameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRandomPlaceByCityNameResponse proto.InternalMessageInfo

func (m *GetRandomPlaceByCityNameResponse) GetPlace() *Place {
	if m != nil {
		return m.Place
	}
	return nil
}

// GetPlacesByCityId
type GetPlacesByCityIDRequest struct {
	CityID               uint64   `protobuf:"varint,1,opt,name=cityID,proto3" json:"cityID,omitempty"`
	Offset               uint64   `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Amount               uint64   `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPlacesByCityIDRequest) Reset()         { *m = GetPlacesByCityIDRequest{} }
func (m *GetPlacesByCityIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetPlacesByCityIDRequest) ProtoMessage()    {}
func (*GetPlacesByCityIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0937d2e70aaf1027, []int{8}
}

func (m *GetPlacesByCityIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPlacesByCityIDRequest.Unmarshal(m, b)
}
func (m *GetPlacesByCityIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPlacesByCityIDRequest.Marshal(b, m, deterministic)
}
func (m *GetPlacesByCityIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPlacesByCityIDRequest.Merge(m, src)
}
func (m *GetPlacesByCityIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetPlacesByCityIDRequest.Size(m)
}
func (m *GetPlacesByCityIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPlacesByCityIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPlacesByCityIDRequest proto.InternalMessageInfo

func (m *GetPlacesByCityIDRequest) GetCityID() uint64 {
	if m != nil {
		return m.CityID
	}
	return 0
}

func (m *GetPlacesByCityIDRequest) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetPlacesByCityIDRequest) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type GetPlacesByCityIDResponse struct {
	Places               []*Place `protobuf:"bytes,1,rep,name=places,proto3" json:"places,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPlacesByCityIDResponse) Reset()         { *m = GetPlacesByCityIDResponse{} }
func (m *GetPlacesByCityIDResponse) String() string { return proto.CompactTextString(m) }
func (*GetPlacesByCityIDResponse) ProtoMessage()    {}
func (*GetPlacesByCityIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0937d2e70aaf1027, []int{9}
}

func (m *GetPlacesByCityIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPlacesByCityIDResponse.Unmarshal(m, b)
}
func (m *GetPlacesByCityIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPlacesByCityIDResponse.Marshal(b, m, deterministic)
}
func (m *GetPlacesByCityIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPlacesByCityIDResponse.Merge(m, src)
}
func (m *GetPlacesByCityIDResponse) XXX_Size() int {
	return xxx_messageInfo_GetPlacesByCityIDResponse.Size(m)
}
func (m *GetPlacesByCityIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPlacesByCityIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPlacesByCityIDResponse proto.InternalMessageInfo

func (m *GetPlacesByCityIDResponse) GetPlaces() []*Place {
	if m != nil {
		return m.Places
	}
	return nil
}

func init() {
	proto.RegisterType((*Place)(nil), "Place")
	proto.RegisterType((*City)(nil), "City")
	proto.RegisterType((*AddPlaceRequest)(nil), "AddPlaceRequest")
	proto.RegisterType((*AddPlaceResponse)(nil), "AddPlaceResponse")
	proto.RegisterType((*GetCitiesRequest)(nil), "GetCitiesRequest")
	proto.RegisterType((*GetCitiesResponse)(nil), "GetCitiesResponse")
	proto.RegisterType((*GetRandomPlaceByCityNameRequest)(nil), "GetRandomPlaceByCityNameRequest")
	proto.RegisterType((*GetRandomPlaceByCityNameResponse)(nil), "GetRandomPlaceByCityNameResponse")
	proto.RegisterType((*GetPlacesByCityIDRequest)(nil), "GetPlacesByCityIDRequest")
	proto.RegisterType((*GetPlacesByCityIDResponse)(nil), "GetPlacesByCityIDResponse")
}

func init() { proto.RegisterFile("places.proto", fileDescriptor_0937d2e70aaf1027) }

var fileDescriptor_0937d2e70aaf1027 = []byte{
	// 422 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0x5f, 0xcb, 0xd3, 0x30,
	0x14, 0xc6, 0x69, 0xd7, 0xd6, 0x77, 0xa7, 0xa2, 0x5b, 0x90, 0x97, 0xbc, 0xc5, 0x3f, 0x35, 0x57,
	0xbb, 0x90, 0x08, 0xf5, 0x52, 0x04, 0xdd, 0x84, 0xe1, 0x1f, 0x44, 0x22, 0x5e, 0x4b, 0xd7, 0x64,
	0x12, 0x58, 0x9b, 0xda, 0x64, 0x17, 0xbb, 0xf4, 0x93, 0xf8, 0x55, 0x65, 0x69, 0x3a, 0xeb, 0xb6,
	0xb2, 0x5d, 0x3e, 0x4f, 0x7a, 0x72, 0x9e, 0xf3, 0xcb, 0x29, 0xdc, 0xaf, 0x37, 0x79, 0x21, 0x34,
	0xad, 0x1b, 0x65, 0x14, 0xf9, 0xed, 0x41, 0xf8, 0x75, 0x6f, 0xa0, 0x07, 0xe0, 0x4b, 0x8e, 0xbd,
	0xd4, 0x9b, 0x05, 0xcc, 0x97, 0x1c, 0x3d, 0x82, 0xd0, 0x48, 0xb3, 0x11, 0xd8, 0x4f, 0xbd, 0xd9,
	0x98, 0xb5, 0x02, 0x61, 0xb8, 0x97, 0x73, 0xde, 0x08, 0xad, 0xf1, 0xc8, 0xfa, 0x9d, 0x44, 0x29,
	0xc4, 0x5c, 0xe8, 0xa2, 0x91, 0xb5, 0x91, 0xaa, 0xc2, 0x81, 0x3d, 0xed, 0x5b, 0xe8, 0x16, 0x22,
	0x59, 0xfe, 0xfc, 0xce, 0x3e, 0xe3, 0xd0, 0x1e, 0x3a, 0x45, 0x5e, 0x40, 0xb0, 0x90, 0x66, 0x77,
	0x5d, 0x02, 0xf2, 0x09, 0x1e, 0xbe, 0xe3, 0xdc, 0x66, 0x66, 0xe2, 0xd7, 0x56, 0x68, 0x83, 0x12,
	0xb8, 0x29, 0xa4, 0xd9, 0x7d, 0xc9, 0x4b, 0x61, 0xcb, 0xc7, 0xec, 0xa0, 0xd1, 0x63, 0x08, 0xed,
	0xc0, 0xf6, 0x92, 0x38, 0x8b, 0x68, 0x5b, 0xd9, 0x9a, 0x84, 0xc0, 0xe4, 0xdf, 0x65, 0xba, 0x56,
	0x95, 0x3e, 0x01, 0x41, 0xe6, 0x30, 0x59, 0x0a, 0xb3, 0x90, 0x46, 0x0a, 0xdd, 0x75, 0xbc, 0x85,
	0x28, 0x2f, 0xd5, 0xb6, 0x32, 0xee, 0x3b, 0xa7, 0xf6, 0xbe, 0x5a, 0xaf, 0xb5, 0x30, 0xb6, 0x5d,
	0xc0, 0x9c, 0x22, 0x19, 0x4c, 0x7b, 0x77, 0xb8, 0x46, 0x4f, 0x20, 0x2a, 0xac, 0x83, 0xbd, 0x74,
	0x34, 0x8b, 0xb3, 0x90, 0xee, 0x31, 0x30, 0x67, 0x92, 0x37, 0xf0, 0x6c, 0x29, 0x0c, 0xcb, 0x2b,
	0xae, 0x4a, 0x9b, 0x70, 0xbe, 0x5b, 0xb8, 0xa9, 0xae, 0x18, 0x9c, 0xbc, 0x85, 0x74, 0xb8, 0xdc,
	0x25, 0x38, 0xc0, 0xf1, 0xce, 0xc1, 0x59, 0x01, 0x5e, 0x0a, 0x63, 0x2d, 0xdd, 0x16, 0x7f, 0x78,
	0xdf, 0x03, 0x50, 0x58, 0xa3, 0x03, 0xd0, 0xaa, 0x21, 0x00, 0x3d, 0x60, 0xa3, 0x3e, 0x30, 0xf2,
	0x1a, 0xee, 0xce, 0xf4, 0x70, 0xf1, 0x9e, 0x42, 0xd4, 0x2e, 0xab, 0x03, 0xd4, 0xe5, 0x73, 0x6e,
	0xf6, 0xc7, 0x87, 0xb8, 0x2d, 0xfd, 0x66, 0x54, 0x23, 0xd0, 0x0f, 0x1b, 0xf8, 0xec, 0xc8, 0x28,
	0xa5, 0x17, 0x60, 0x26, 0xcf, 0xe9, 0x45, 0x5e, 0x19, 0x8c, 0x0f, 0xcf, 0x88, 0xa6, 0xf4, 0x78,
	0x2d, 0x12, 0x44, 0x4f, 0x5f, 0xf9, 0x25, 0xdc, 0x74, 0x2b, 0x86, 0x26, 0xf4, 0x68, 0x75, 0x93,
	0x29, 0x3d, 0xd9, 0xbf, 0x8f, 0x76, 0x57, 0xfe, 0x47, 0x82, 0xee, 0xe8, 0xd0, 0x53, 0x24, 0x09,
	0x1d, 0x24, 0xb8, 0x8a, 0xec, 0x5f, 0xfe, 0xea, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x76, 0xc9,
	0x35, 0x1a, 0xf5, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PlacesStoreClient is the client API for PlacesStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PlacesStoreClient interface {
	GetRandomPlaceByCityName(ctx context.Context, in *GetRandomPlaceByCityNameRequest, opts ...grpc.CallOption) (*GetRandomPlaceByCityNameResponse, error)
	GetCities(ctx context.Context, in *GetCitiesRequest, opts ...grpc.CallOption) (*GetCitiesResponse, error)
	AddPlace(ctx context.Context, in *AddPlaceRequest, opts ...grpc.CallOption) (*AddPlaceResponse, error)
	GetPlacesByCityID(ctx context.Context, in *GetPlacesByCityIDRequest, opts ...grpc.CallOption) (*GetPlacesByCityIDResponse, error)
}

type placesStoreClient struct {
	cc grpc.ClientConnInterface
}

func NewPlacesStoreClient(cc grpc.ClientConnInterface) PlacesStoreClient {
	return &placesStoreClient{cc}
}

func (c *placesStoreClient) GetRandomPlaceByCityName(ctx context.Context, in *GetRandomPlaceByCityNameRequest, opts ...grpc.CallOption) (*GetRandomPlaceByCityNameResponse, error) {
	out := new(GetRandomPlaceByCityNameResponse)
	err := c.cc.Invoke(ctx, "/PlacesStore/GetRandomPlaceByCityName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *placesStoreClient) GetCities(ctx context.Context, in *GetCitiesRequest, opts ...grpc.CallOption) (*GetCitiesResponse, error) {
	out := new(GetCitiesResponse)
	err := c.cc.Invoke(ctx, "/PlacesStore/GetCities", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *placesStoreClient) AddPlace(ctx context.Context, in *AddPlaceRequest, opts ...grpc.CallOption) (*AddPlaceResponse, error) {
	out := new(AddPlaceResponse)
	err := c.cc.Invoke(ctx, "/PlacesStore/AddPlace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *placesStoreClient) GetPlacesByCityID(ctx context.Context, in *GetPlacesByCityIDRequest, opts ...grpc.CallOption) (*GetPlacesByCityIDResponse, error) {
	out := new(GetPlacesByCityIDResponse)
	err := c.cc.Invoke(ctx, "/PlacesStore/GetPlacesByCityID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlacesStoreServer is the server API for PlacesStore service.
type PlacesStoreServer interface {
	GetRandomPlaceByCityName(context.Context, *GetRandomPlaceByCityNameRequest) (*GetRandomPlaceByCityNameResponse, error)
	GetCities(context.Context, *GetCitiesRequest) (*GetCitiesResponse, error)
	AddPlace(context.Context, *AddPlaceRequest) (*AddPlaceResponse, error)
	GetPlacesByCityID(context.Context, *GetPlacesByCityIDRequest) (*GetPlacesByCityIDResponse, error)
}

// UnimplementedPlacesStoreServer can be embedded to have forward compatible implementations.
type UnimplementedPlacesStoreServer struct {
}

func (*UnimplementedPlacesStoreServer) GetRandomPlaceByCityName(ctx context.Context, req *GetRandomPlaceByCityNameRequest) (*GetRandomPlaceByCityNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRandomPlaceByCityName not implemented")
}
func (*UnimplementedPlacesStoreServer) GetCities(ctx context.Context, req *GetCitiesRequest) (*GetCitiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCities not implemented")
}
func (*UnimplementedPlacesStoreServer) AddPlace(ctx context.Context, req *AddPlaceRequest) (*AddPlaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPlace not implemented")
}
func (*UnimplementedPlacesStoreServer) GetPlacesByCityID(ctx context.Context, req *GetPlacesByCityIDRequest) (*GetPlacesByCityIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlacesByCityID not implemented")
}

func RegisterPlacesStoreServer(s *grpc.Server, srv PlacesStoreServer) {
	s.RegisterService(&_PlacesStore_serviceDesc, srv)
}

func _PlacesStore_GetRandomPlaceByCityName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRandomPlaceByCityNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlacesStoreServer).GetRandomPlaceByCityName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PlacesStore/GetRandomPlaceByCityName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlacesStoreServer).GetRandomPlaceByCityName(ctx, req.(*GetRandomPlaceByCityNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlacesStore_GetCities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlacesStoreServer).GetCities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PlacesStore/GetCities",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlacesStoreServer).GetCities(ctx, req.(*GetCitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlacesStore_AddPlace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPlaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlacesStoreServer).AddPlace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PlacesStore/AddPlace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlacesStoreServer).AddPlace(ctx, req.(*AddPlaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlacesStore_GetPlacesByCityID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlacesByCityIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlacesStoreServer).GetPlacesByCityID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PlacesStore/GetPlacesByCityID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlacesStoreServer).GetPlacesByCityID(ctx, req.(*GetPlacesByCityIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PlacesStore_serviceDesc = grpc.ServiceDesc{
	ServiceName: "PlacesStore",
	HandlerType: (*PlacesStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRandomPlaceByCityName",
			Handler:    _PlacesStore_GetRandomPlaceByCityName_Handler,
		},
		{
			MethodName: "GetCities",
			Handler:    _PlacesStore_GetCities_Handler,
		},
		{
			MethodName: "AddPlace",
			Handler:    _PlacesStore_AddPlace_Handler,
		},
		{
			MethodName: "GetPlacesByCityID",
			Handler:    _PlacesStore_GetPlacesByCityID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "places.proto",
}
